---
title: "Linear Regression"
author: "Emilio Garcia"
date: "5/30/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Data
```{r}
df <- read.csv("Admission_Predict_Ver1.1.csv", stringsAsFactors = FALSE)
```

GRE Score
```{r}
set.seed(5312020)
# Linear regression model
lin_model_gre = lm(Chance.of.Admit~GRE.Score, data=df)
summary(lin_model_gre)
plot(x= df$GRE.Score, y=df$Chance.of.Admit)
abline(lin_model_gre, col="red", lwd=5)
y_predict = predict(lin_model_gre)
fit_coeff = lin_model_gre$coefficients
n = nrow(df)
B = 10000
  # Residual plot
plot(x=df$GRE.Score, y=lin_model_gre$residuals)

  # 90% CI of the slope
slope_fit = summary(lin_model_gre)$coeff[2,1]
slope_se = summary(lin_model_gre)$coeff[2,2]
slope_fit-qnorm(0.95)*slope_se
    # lower bound
slope_fit+qnorm(0.95)*slope_se
    # upper bound

# Empirical Bootstrap
coeff_BT = matrix(NA, nrow=B, ncol=2)
for(i_BT in 1:B){
  w = sample(n,n,replace=T)
  data1_BT = df[w,]
  fit_BT = lm(Chance.of.Admit~GRE.Score, data=data1_BT)
  coeff_BT[i_BT,] = fit_BT$coefficients
}
colnames(coeff_BT) = c("Intercept","Slope")
  # Histogram for intercept
hist(coeff_BT[,'Intercept'], col="tan")
abline(v=fit_coeff[1], lwd=6, col="purple")
  # Histogram for slope
hist(coeff_BT[,'Slope'], col="palegreen")
abline(v=fit_coeff[2], lwd=6, col="brown")
  # Plot
plot(coeff_BT, cex=0.5)
points(x=fit_coeff[1], y=fit_coeff[2], cex=5, pch="+", col="red")

# Residual Bootstrap
coeff_BT_res = matrix(NA, nrow=B, ncol=2)
for(i_BT in 1:B){
  w = sample(n,n,replace=T)
  y_bt = y_predict+lin_model_gre$residuals[w]
  data1_BT = data.frame(GRE.Score=df$GRE.Score,
                        Chance.of.Admit=y_bt)
  fit_BT = lm(Chance.of.Admit~GRE.Score, data=data1_BT)
  coeff_BT_res[i_BT,] = fit_BT$coefficients
}
colnames(coeff_BT_res) = c("Intercept","Slope")
  # Histogram for intercept
hist(coeff_BT_res[,'Intercept'], col="tan")
abline(v=fit_coeff[1], lwd=6, col="purple")
  # Histogram for slope
hist(coeff_BT_res[,'Slope'], col="palegreen")
abline(v=fit_coeff[2], lwd=6, col="brown")
  # Plot
plot(coeff_BT_res, cex=0.5)
points(x=fit_coeff[1], y=fit_coeff[2], cex=5, pch="+", col="red")

# Wild bootstrap
B = 10000
coeff_BT_wild = matrix(NA, nrow=B, ncol=2)
for(i_BT in 1:B){
  w = sample(n,n,replace=T)
  y_bt = y_predict+rnorm(n, sd=abs(lin_model_gre$residuals))
  data1_BT = data.frame(GRE.Score=df$GRE.Score,
                        Chance.of.Admit=y_bt)
  fit_BT = lm(Chance.of.Admit~GRE.Score, data=data1_BT)
  coeff_BT_wild[i_BT,] = fit_BT$coefficients
}
colnames(coeff_BT_wild) = c("Intercept","Slope")
  # Histogram for intercept
hist(coeff_BT_wild[,'Intercept'], col="tan")
abline(v=fit_coeff[1], lwd=6, col="purple")
  # Histogram for slope
hist(coeff_BT_wild[,'Slope'], col="palegreen")
abline(v=fit_coeff[2], lwd=6, col="brown")
  # Plot
plot(coeff_BT_wild, cex=0.5)
points(x=fit_coeff[1], y=fit_coeff[2], cex=5, pch="+", col="red")

# Result comparisons
  # Variances #
    # Empirical
var(coeff_BT[,'Intercept'])
var(coeff_BT[,'Slope'])
    # Residual
var(coeff_BT_res[,'Intercept'])
var(coeff_BT_res[,'Slope'])
    # Wild
var(coeff_BT_wild[,'Intercept'])
var(coeff_BT_wild[,'Slope'])
  # MSEs #
    # Empirical
mean((coeff_BT[,'Intercept']-fit_coeff[1])^2)
mean((coeff_BT[,'Slope']-fit_coeff[2])^2)
    # Residual
mean((coeff_BT_res[,'Intercept']-fit_coeff[1])^2)
mean((coeff_BT_res[,'Slope']-fit_coeff[2])^2)
    # Wild
mean((coeff_BT_wild[,'Intercept']-fit_coeff[1])^2)
mean((coeff_BT_wild[,'Slope']-fit_coeff[2])^2)
  # Quantile CIs #
    # Asymptotic model-based theory
confint(lin_model_gre,level = 0.9)
    # Empirical
quantile(coeff_BT[,'Intercept'],c(0.05,0.95))
quantile(coeff_BT[,'Slope'],c(0.05,0.95))
    # Residual
quantile(coeff_BT_res[,'Intercept'],c(0.05,0.95))
quantile(coeff_BT_res[,'Slope'],c(0.05,0.95))
    # Wild
quantile(coeff_BT_wild[,'Intercept'],c(0.05,0.95))
quantile(coeff_BT_wild[,'Slope'],c(0.05,0.95))

  # Boxplots
    # Intercept
intercepts <- list(Empirical=coeff_BT[,'Intercept'], Residual=coeff_BT_res[,'Intercept'], Wild=coeff_BT_wild[,'Intercept'])
box_int=boxplot(intercepts,outline=FALSE,boxwex=0.25,ylab="Intercept",col="gray",plot=FALSE)
bxp(box_int,axes=FALSE)
axis(2)
axis(1,tick=FALSE,labels=c("Empirical","Residual", "Wild"),at=1:3)
stripchart(intercepts,vertical=TRUE,pch=16,col="orange",method="jitter",add=TRUE)
    # Slope
slopes <- list(Empirical=coeff_BT[,'Slope'], Residual=coeff_BT_res[,'Slope'], Wild=coeff_BT_wild[,'Slope'])
box_slope=boxplot(slopes,outline=FALSE,boxwex=0.25,ylab="Slope",col="gray",plot=FALSE)
bxp(box_slope,axes=FALSE)
axis(2)
axis(1,tick=FALSE,labels=c("Empirical","Residual", "Wild"),at=1:3)
stripchart(slopes,vertical=TRUE,pch=16,col="light blue",method="jitter",add=TRUE)
```

TOEFL Score
```{r}
set.seed(5312020)
# Linear regression model
lin_model_gre = lm(Chance.of.Admit~TOEFL.Score, data=df)
summary(lin_model_gre)
plot(x= df$TOEFL.Score, y=df$Chance.of.Admit)
abline(lin_model_gre, col="red", lwd=5)
y_predict = predict(lin_model_gre)
fit_coeff = lin_model_gre$coefficients
n = nrow(df)
B = 10000
# Residual plot
plot(x=df$TOEFL.Score, y=lin_model_gre$residuals)

# 90% CI of the slope
slope_fit = summary(lin_model_gre)$coeff[2,1]
slope_se = summary(lin_model_gre)$coeff[2,2]
slope_fit-qnorm(0.95)*slope_se
# lower bound
slope_fit+qnorm(0.95)*slope_se
# upper bound

# Empirical Bootstrap
coeff_BT = matrix(NA, nrow=B, ncol=2)
for(i_BT in 1:B){
  w = sample(n,n,replace=T)
  data1_BT = df[w,]
  fit_BT = lm(Chance.of.Admit~TOEFL.Score, data=data1_BT)
  coeff_BT[i_BT,] = fit_BT$coefficients
}
colnames(coeff_BT) = c("Intercept","Slope")
# Histogram for intercept
hist(coeff_BT[,'Intercept'], col="tan")
abline(v=fit_coeff[1], lwd=6, col="purple")
# Histogram for slope
hist(coeff_BT[,'Slope'], col="palegreen")
abline(v=fit_coeff[2], lwd=6, col="brown")
# Plot
plot(coeff_BT, cex=0.5)
points(x=fit_coeff[1], y=fit_coeff[2], cex=5, pch="+", col="red")

# Residual Bootstrap
coeff_BT_res = matrix(NA, nrow=B, ncol=2)
for(i_BT in 1:B){
  w = sample(n,n,replace=T)
  y_bt = y_predict+lin_model_gre$residuals[w]
  data1_BT = data.frame(TOEFL.Score=df$TOEFL.Score,
                        Chance.of.Admit=y_bt)
  fit_BT = lm(Chance.of.Admit~TOEFL.Score, data=data1_BT)
  coeff_BT_res[i_BT,] = fit_BT$coefficients
}
colnames(coeff_BT_res) = c("Intercept","Slope")
# Histogram for intercept
hist(coeff_BT_res[,'Intercept'], col="tan")
abline(v=fit_coeff[1], lwd=6, col="purple")
# Histogram for slope
hist(coeff_BT_res[,'Slope'], col="palegreen")
abline(v=fit_coeff[2], lwd=6, col="brown")
# Plot
plot(coeff_BT_res, cex=0.5)
points(x=fit_coeff[1], y=fit_coeff[2], cex=5, pch="+", col="red")

# Wild bootstrap
B = 10000
coeff_BT_wild = matrix(NA, nrow=B, ncol=2)
for(i_BT in 1:B){
  w = sample(n,n,replace=T)
  y_bt = y_predict+rnorm(n, sd=abs(lin_model_gre$residuals))
  data1_BT = data.frame(TOEFL.Score=df$TOEFL.Score,
                        Chance.of.Admit=y_bt)
  fit_BT = lm(Chance.of.Admit~TOEFL.Score, data=data1_BT)
  coeff_BT_wild[i_BT,] = fit_BT$coefficients
}
colnames(coeff_BT_wild) = c("Intercept","Slope")
# Histogram for intercept
hist(coeff_BT_wild[,'Intercept'], col="tan")
abline(v=fit_coeff[1], lwd=6, col="purple")
# Histogram for slope
hist(coeff_BT_wild[,'Slope'], col="palegreen")
abline(v=fit_coeff[2], lwd=6, col="brown")
# Plot
plot(coeff_BT_wild, cex=0.5)
points(x=fit_coeff[1], y=fit_coeff[2], cex=5, pch="+", col="red")

# Result comparisons
# Variances #
# Empirical
var(coeff_BT[,'Intercept'])
var(coeff_BT[,'Slope'])
# Residual
var(coeff_BT_res[,'Intercept'])
var(coeff_BT_res[,'Slope'])
# Wild
var(coeff_BT_wild[,'Intercept'])
var(coeff_BT_wild[,'Slope'])
# MSEs #
# Empirical
mean((coeff_BT[,'Intercept']-fit_coeff[1])^2)
mean((coeff_BT[,'Slope']-fit_coeff[2])^2)
# Residual
mean((coeff_BT_res[,'Intercept']-fit_coeff[1])^2)
mean((coeff_BT_res[,'Slope']-fit_coeff[2])^2)
# Wild
mean((coeff_BT_wild[,'Intercept']-fit_coeff[1])^2)
mean((coeff_BT_wild[,'Slope']-fit_coeff[2])^2)
# Quantile CIs #
# Asymptotic model-based theory
confint(lin_model_gre,level = 0.9)
# Empirical
quantile(coeff_BT[,'Intercept'],c(0.05,0.95))
quantile(coeff_BT[,'Slope'],c(0.05,0.95))
# Residual
quantile(coeff_BT_res[,'Intercept'],c(0.05,0.95))
quantile(coeff_BT_res[,'Slope'],c(0.05,0.95))
# Wild
quantile(coeff_BT_wild[,'Intercept'],c(0.05,0.95))
quantile(coeff_BT_wild[,'Slope'],c(0.05,0.95))

# Boxplots
# Intercept
intercepts <- list(Empirical=coeff_BT[,'Intercept'], Residual=coeff_BT_res[,'Intercept'], Wild=coeff_BT_wild[,'Intercept'])
box_int=boxplot(intercepts,outline=FALSE,boxwex=0.25,ylab="Intercept",col="gray",plot=FALSE)
bxp(box_int,axes=FALSE)
axis(2)
axis(1,tick=FALSE,labels=c("Empirical","Residual", "Wild"),at=1:3)
stripchart(intercepts,vertical=TRUE,pch=16,col="orange",method="jitter",add=TRUE)
# Slope
slopes <- list(Empirical=coeff_BT[,'Slope'], Residual=coeff_BT_res[,'Slope'], Wild=coeff_BT_wild[,'Slope'])
box_slope=boxplot(slopes,outline=FALSE,boxwex=0.25,ylab="Slope",col="gray",plot=FALSE)
bxp(box_slope,axes=FALSE)
axis(2)
axis(1,tick=FALSE,labels=c("Empirical","Residual", "Wild"),at=1:3)
stripchart(slopes,vertical=TRUE,pch=16,col="light blue",method="jitter",add=TRUE)
```

University Rating
```{r}
set.seed(5312020)
# Linear regression model
lin_model_gre = lm(Chance.of.Admit~University.Rating, data=df)
summary(lin_model_gre)
plot(x= df$University.Rating, y=df$Chance.of.Admit)
abline(lin_model_gre, col="red", lwd=5)
y_predict = predict(lin_model_gre)
fit_coeff = lin_model_gre$coefficients
n = nrow(df)
B = 10000
# Residual plot
plot(x=df$University.Rating, y=lin_model_gre$residuals)

# 90% CI of the slope
slope_fit = summary(lin_model_gre)$coeff[2,1]
slope_se = summary(lin_model_gre)$coeff[2,2]
slope_fit-qnorm(0.95)*slope_se
# lower bound
slope_fit+qnorm(0.95)*slope_se
# upper bound

# Empirical Bootstrap
coeff_BT = matrix(NA, nrow=B, ncol=2)
for(i_BT in 1:B){
  w = sample(n,n,replace=T)
  data1_BT = df[w,]
  fit_BT = lm(Chance.of.Admit~University.Rating, data=data1_BT)
  coeff_BT[i_BT,] = fit_BT$coefficients
}
colnames(coeff_BT) = c("Intercept","Slope")
# Histogram for intercept
hist(coeff_BT[,'Intercept'], col="tan")
abline(v=fit_coeff[1], lwd=6, col="purple")
# Histogram for slope
hist(coeff_BT[,'Slope'], col="palegreen")
abline(v=fit_coeff[2], lwd=6, col="brown")
# Plot
plot(coeff_BT, cex=0.5)
points(x=fit_coeff[1], y=fit_coeff[2], cex=5, pch="+", col="red")

# Residual Bootstrap
coeff_BT_res = matrix(NA, nrow=B, ncol=2)
for(i_BT in 1:B){
  w = sample(n,n,replace=T)
  y_bt = y_predict+lin_model_gre$residuals[w]
  data1_BT = data.frame(University.Rating=df$University.Rating,
                        Chance.of.Admit=y_bt)
  fit_BT = lm(Chance.of.Admit~University.Rating, data=data1_BT)
  coeff_BT_res[i_BT,] = fit_BT$coefficients
}
colnames(coeff_BT_res) = c("Intercept","Slope")
# Histogram for intercept
hist(coeff_BT_res[,'Intercept'], col="tan")
abline(v=fit_coeff[1], lwd=6, col="purple")
# Histogram for slope
hist(coeff_BT_res[,'Slope'], col="palegreen")
abline(v=fit_coeff[2], lwd=6, col="brown")
# Plot
plot(coeff_BT_res, cex=0.5)
points(x=fit_coeff[1], y=fit_coeff[2], cex=5, pch="+", col="red")

# Wild bootstrap
B = 10000
coeff_BT_wild = matrix(NA, nrow=B, ncol=2)
for(i_BT in 1:B){
  w = sample(n,n,replace=T)
  y_bt = y_predict+rnorm(n, sd=abs(lin_model_gre$residuals))
  data1_BT = data.frame(University.Rating=df$University.Rating,
                        Chance.of.Admit=y_bt)
  fit_BT = lm(Chance.of.Admit~University.Rating, data=data1_BT)
  coeff_BT_wild[i_BT,] = fit_BT$coefficients
}
colnames(coeff_BT_wild) = c("Intercept","Slope")
# Histogram for intercept
hist(coeff_BT_wild[,'Intercept'], col="tan")
abline(v=fit_coeff[1], lwd=6, col="purple")
# Histogram for slope
hist(coeff_BT_wild[,'Slope'], col="palegreen")
abline(v=fit_coeff[2], lwd=6, col="brown")
# Plot
plot(coeff_BT_wild, cex=0.5)
points(x=fit_coeff[1], y=fit_coeff[2], cex=5, pch="+", col="red")

# Result comparisons
# Variances #
# Empirical
var(coeff_BT[,'Intercept'])
var(coeff_BT[,'Slope'])
# Residual
var(coeff_BT_res[,'Intercept'])
var(coeff_BT_res[,'Slope'])
# Wild
var(coeff_BT_wild[,'Intercept'])
var(coeff_BT_wild[,'Slope'])
# MSEs #
# Empirical
mean((coeff_BT[,'Intercept']-fit_coeff[1])^2)
mean((coeff_BT[,'Slope']-fit_coeff[2])^2)
# Residual
mean((coeff_BT_res[,'Intercept']-fit_coeff[1])^2)
mean((coeff_BT_res[,'Slope']-fit_coeff[2])^2)
# Wild
mean((coeff_BT_wild[,'Intercept']-fit_coeff[1])^2)
mean((coeff_BT_wild[,'Slope']-fit_coeff[2])^2)
# Quantile CIs #
# Asymptotic model-based theory
confint(lin_model_gre,level = 0.9)
# Empirical
quantile(coeff_BT[,'Intercept'],c(0.05,0.95))
quantile(coeff_BT[,'Slope'],c(0.05,0.95))
# Residual
quantile(coeff_BT_res[,'Intercept'],c(0.05,0.95))
quantile(coeff_BT_res[,'Slope'],c(0.05,0.95))
# Wild
quantile(coeff_BT_wild[,'Intercept'],c(0.05,0.95))
quantile(coeff_BT_wild[,'Slope'],c(0.05,0.95))

# Boxplots
# Intercept
intercepts <- list(Empirical=coeff_BT[,'Intercept'], Residual=coeff_BT_res[,'Intercept'], Wild=coeff_BT_wild[,'Intercept'])
box_int=boxplot(intercepts,outline=FALSE,boxwex=0.25,ylab="Intercept",col="gray",plot=FALSE)
bxp(box_int,axes=FALSE)
axis(2)
axis(1,tick=FALSE,labels=c("Empirical","Residual", "Wild"),at=1:3)
stripchart(intercepts,vertical=TRUE,pch=16,col="orange",method="jitter",add=TRUE)
# Slope
slopes <- list(Empirical=coeff_BT[,'Slope'], Residual=coeff_BT_res[,'Slope'], Wild=coeff_BT_wild[,'Slope'])
box_slope=boxplot(slopes,outline=FALSE,boxwex=0.25,ylab="Slope",col="gray",plot=FALSE)
bxp(box_slope,axes=FALSE)
axis(2)
axis(1,tick=FALSE,labels=c("Empirical","Residual", "Wild"),at=1:3)
stripchart(slopes,vertical=TRUE,pch=16,col="light blue",method="jitter",add=TRUE)
```

Statement of Purpose
```{r}
set.seed(5312020)
# Linear regression model
lin_model_gre = lm(Chance.of.Admit~SOP, data=df)
summary(lin_model_gre)
plot(x= df$SOP, y=df$Chance.of.Admit)
abline(lin_model_gre, col="red", lwd=5)
y_predict = predict(lin_model_gre)
fit_coeff = lin_model_gre$coefficients
n = nrow(df)
B = 10000
# Residual plot
plot(x=df$SOP, y=lin_model_gre$residuals)

# 90% CI of the slope
slope_fit = summary(lin_model_gre)$coeff[2,1]
slope_se = summary(lin_model_gre)$coeff[2,2]
slope_fit-qnorm(0.95)*slope_se
# lower bound
slope_fit+qnorm(0.95)*slope_se
# upper bound

# Empirical Bootstrap
coeff_BT = matrix(NA, nrow=B, ncol=2)
for(i_BT in 1:B){
  w = sample(n,n,replace=T)
  data1_BT = df[w,]
  fit_BT = lm(Chance.of.Admit~SOP, data=data1_BT)
  coeff_BT[i_BT,] = fit_BT$coefficients
}
colnames(coeff_BT) = c("Intercept","Slope")
# Histogram for intercept
hist(coeff_BT[,'Intercept'], col="tan")
abline(v=fit_coeff[1], lwd=6, col="purple")
# Histogram for slope
hist(coeff_BT[,'Slope'], col="palegreen")
abline(v=fit_coeff[2], lwd=6, col="brown")
# Plot
plot(coeff_BT, cex=0.5)
points(x=fit_coeff[1], y=fit_coeff[2], cex=5, pch="+", col="red")

# Residual Bootstrap
coeff_BT_res = matrix(NA, nrow=B, ncol=2)
for(i_BT in 1:B){
  w = sample(n,n,replace=T)
  y_bt = y_predict+lin_model_gre$residuals[w]
  data1_BT = data.frame(SOP=df$SOP,
                        Chance.of.Admit=y_bt)
  fit_BT = lm(Chance.of.Admit~SOP, data=data1_BT)
  coeff_BT_res[i_BT,] = fit_BT$coefficients
}
colnames(coeff_BT_res) = c("Intercept","Slope")
# Histogram for intercept
hist(coeff_BT_res[,'Intercept'], col="tan")
abline(v=fit_coeff[1], lwd=6, col="purple")
# Histogram for slope
hist(coeff_BT_res[,'Slope'], col="palegreen")
abline(v=fit_coeff[2], lwd=6, col="brown")
# Plot
plot(coeff_BT_res, cex=0.5)
points(x=fit_coeff[1], y=fit_coeff[2], cex=5, pch="+", col="red")

# Wild bootstrap
B = 10000
coeff_BT_wild = matrix(NA, nrow=B, ncol=2)
for(i_BT in 1:B){
  w = sample(n,n,replace=T)
  y_bt = y_predict+rnorm(n, sd=abs(lin_model_gre$residuals))
  data1_BT = data.frame(SOP=df$SOP,
                        Chance.of.Admit=y_bt)
  fit_BT = lm(Chance.of.Admit~SOP, data=data1_BT)
  coeff_BT_wild[i_BT,] = fit_BT$coefficients
}
colnames(coeff_BT_wild) = c("Intercept","Slope")
# Histogram for intercept
hist(coeff_BT_wild[,'Intercept'], col="tan")
abline(v=fit_coeff[1], lwd=6, col="purple")
# Histogram for slope
hist(coeff_BT_wild[,'Slope'], col="palegreen")
abline(v=fit_coeff[2], lwd=6, col="brown")
# Plot
plot(coeff_BT_wild, cex=0.5)
points(x=fit_coeff[1], y=fit_coeff[2], cex=5, pch="+", col="red")

# Result comparisons
# Variances #
# Empirical
var(coeff_BT[,'Intercept'])
var(coeff_BT[,'Slope'])
# Residual
var(coeff_BT_res[,'Intercept'])
var(coeff_BT_res[,'Slope'])
# Wild
var(coeff_BT_wild[,'Intercept'])
var(coeff_BT_wild[,'Slope'])
# MSEs #
# Empirical
mean((coeff_BT[,'Intercept']-fit_coeff[1])^2)
mean((coeff_BT[,'Slope']-fit_coeff[2])^2)
# Residual
mean((coeff_BT_res[,'Intercept']-fit_coeff[1])^2)
mean((coeff_BT_res[,'Slope']-fit_coeff[2])^2)
# Wild
mean((coeff_BT_wild[,'Intercept']-fit_coeff[1])^2)
mean((coeff_BT_wild[,'Slope']-fit_coeff[2])^2)
# Quantile CIs #
# Asymptotic model-based theory
confint(lin_model_gre,level = 0.9)
# Empirical
quantile(coeff_BT[,'Intercept'],c(0.05,0.95))
quantile(coeff_BT[,'Slope'],c(0.05,0.95))
# Residual
quantile(coeff_BT_res[,'Intercept'],c(0.05,0.95))
quantile(coeff_BT_res[,'Slope'],c(0.05,0.95))
# Wild
quantile(coeff_BT_wild[,'Intercept'],c(0.05,0.95))
quantile(coeff_BT_wild[,'Slope'],c(0.05,0.95))

# Boxplots
# Intercept
intercepts <- list(Empirical=coeff_BT[,'Intercept'], Residual=coeff_BT_res[,'Intercept'], Wild=coeff_BT_wild[,'Intercept'])
box_int=boxplot(intercepts,outline=FALSE,boxwex=0.25,ylab="Intercept",col="gray",plot=FALSE)
bxp(box_int,axes=FALSE)
axis(2)
axis(1,tick=FALSE,labels=c("Empirical","Residual", "Wild"),at=1:3)
stripchart(intercepts,vertical=TRUE,pch=16,col="orange",method="jitter",add=TRUE)
# Slope
slopes <- list(Empirical=coeff_BT[,'Slope'], Residual=coeff_BT_res[,'Slope'], Wild=coeff_BT_wild[,'Slope'])
box_slope=boxplot(slopes,outline=FALSE,boxwex=0.25,ylab="Slope",col="gray",plot=FALSE)
bxp(box_slope,axes=FALSE)
axis(2)
axis(1,tick=FALSE,labels=c("Empirical","Residual", "Wild"),at=1:3)
stripchart(slopes,vertical=TRUE,pch=16,col="light blue",method="jitter",add=TRUE)
```

Letter of Recommendation
```{r}
set.seed(5312020)
# Linear regression model
lin_model_gre = lm(Chance.of.Admit~LOR, data=df)
summary(lin_model_gre)
plot(x= df$LOR, y=df$Chance.of.Admit)
abline(lin_model_gre, col="red", lwd=5)
y_predict = predict(lin_model_gre)
fit_coeff = lin_model_gre$coefficients
n = nrow(df)
B = 10000
# Residual plot
plot(x=df$LOR, y=lin_model_gre$residuals)

# 90% CI of the slope
slope_fit = summary(lin_model_gre)$coeff[2,1]
slope_se = summary(lin_model_gre)$coeff[2,2]
slope_fit-qnorm(0.95)*slope_se
# lower bound
slope_fit+qnorm(0.95)*slope_se
# upper bound

# Empirical Bootstrap
coeff_BT = matrix(NA, nrow=B, ncol=2)
for(i_BT in 1:B){
  w = sample(n,n,replace=T)
  data1_BT = df[w,]
  fit_BT = lm(Chance.of.Admit~LOR, data=data1_BT)
  coeff_BT[i_BT,] = fit_BT$coefficients
}
colnames(coeff_BT) = c("Intercept","Slope")
# Histogram for intercept
hist(coeff_BT[,'Intercept'], col="tan")
abline(v=fit_coeff[1], lwd=6, col="purple")
# Histogram for slope
hist(coeff_BT[,'Slope'], col="palegreen")
abline(v=fit_coeff[2], lwd=6, col="brown")
# Plot
plot(coeff_BT, cex=0.5)
points(x=fit_coeff[1], y=fit_coeff[2], cex=5, pch="+", col="red")

# Residual Bootstrap
coeff_BT_res = matrix(NA, nrow=B, ncol=2)
for(i_BT in 1:B){
  w = sample(n,n,replace=T)
  y_bt = y_predict+lin_model_gre$residuals[w]
  data1_BT = data.frame(LOR=df$LOR,
                        Chance.of.Admit=y_bt)
  fit_BT = lm(Chance.of.Admit~LOR, data=data1_BT)
  coeff_BT_res[i_BT,] = fit_BT$coefficients
}
colnames(coeff_BT_res) = c("Intercept","Slope")
# Histogram for intercept
hist(coeff_BT_res[,'Intercept'], col="tan")
abline(v=fit_coeff[1], lwd=6, col="purple")
# Histogram for slope
hist(coeff_BT_res[,'Slope'], col="palegreen")
abline(v=fit_coeff[2], lwd=6, col="brown")
# Plot
plot(coeff_BT_res, cex=0.5)
points(x=fit_coeff[1], y=fit_coeff[2], cex=5, pch="+", col="red")

# Wild bootstrap
B = 10000
coeff_BT_wild = matrix(NA, nrow=B, ncol=2)
for(i_BT in 1:B){
  w = sample(n,n,replace=T)
  y_bt = y_predict+rnorm(n, sd=abs(lin_model_gre$residuals))
  data1_BT = data.frame(LOR=df$LOR,
                        Chance.of.Admit=y_bt)
  fit_BT = lm(Chance.of.Admit~LOR, data=data1_BT)
  coeff_BT_wild[i_BT,] = fit_BT$coefficients
}
colnames(coeff_BT_wild) = c("Intercept","Slope")
# Histogram for intercept
hist(coeff_BT_wild[,'Intercept'], col="tan")
abline(v=fit_coeff[1], lwd=6, col="purple")
# Histogram for slope
hist(coeff_BT_wild[,'Slope'], col="palegreen")
abline(v=fit_coeff[2], lwd=6, col="brown")
# Plot
plot(coeff_BT_wild, cex=0.5)
points(x=fit_coeff[1], y=fit_coeff[2], cex=5, pch="+", col="red")

# Result comparisons
# Variances #
# Empirical
var(coeff_BT[,'Intercept'])
var(coeff_BT[,'Slope'])
# Residual
var(coeff_BT_res[,'Intercept'])
var(coeff_BT_res[,'Slope'])
# Wild
var(coeff_BT_wild[,'Intercept'])
var(coeff_BT_wild[,'Slope'])
# MSEs #
# Empirical
mean((coeff_BT[,'Intercept']-fit_coeff[1])^2)
mean((coeff_BT[,'Slope']-fit_coeff[2])^2)
# Residual
mean((coeff_BT_res[,'Intercept']-fit_coeff[1])^2)
mean((coeff_BT_res[,'Slope']-fit_coeff[2])^2)
# Wild
mean((coeff_BT_wild[,'Intercept']-fit_coeff[1])^2)
mean((coeff_BT_wild[,'Slope']-fit_coeff[2])^2)
# Quantile CIs #
# Asymptotic model-based theory
confint(lin_model_gre,level = 0.9)
# Empirical
quantile(coeff_BT[,'Intercept'],c(0.05,0.95))
quantile(coeff_BT[,'Slope'],c(0.05,0.95))
# Residual
quantile(coeff_BT_res[,'Intercept'],c(0.05,0.95))
quantile(coeff_BT_res[,'Slope'],c(0.05,0.95))
# Wild
quantile(coeff_BT_wild[,'Intercept'],c(0.05,0.95))
quantile(coeff_BT_wild[,'Slope'],c(0.05,0.95))

# Boxplots
# Intercept
intercepts <- list(Empirical=coeff_BT[,'Intercept'], Residual=coeff_BT_res[,'Intercept'], Wild=coeff_BT_wild[,'Intercept'])
box_int=boxplot(intercepts,outline=FALSE,boxwex=0.25,ylab="Intercept",col="gray",plot=FALSE)
bxp(box_int,axes=FALSE)
axis(2)
axis(1,tick=FALSE,labels=c("Empirical","Residual", "Wild"),at=1:3)
stripchart(intercepts,vertical=TRUE,pch=16,col="orange",method="jitter",add=TRUE)
# Slope
slopes <- list(Empirical=coeff_BT[,'Slope'], Residual=coeff_BT_res[,'Slope'], Wild=coeff_BT_wild[,'Slope'])
box_slope=boxplot(slopes,outline=FALSE,boxwex=0.25,ylab="Slope",col="gray",plot=FALSE)
bxp(box_slope,axes=FALSE)
axis(2)
axis(1,tick=FALSE,labels=c("Empirical","Residual", "Wild"),at=1:3)
stripchart(slopes,vertical=TRUE,pch=16,col="light blue",method="jitter",add=TRUE)
```

GPA
```{r}
set.seed(5312020)
# Linear regression model
lin_model_gre = lm(Chance.of.Admit~CGPA, data=df)
summary(lin_model_gre)
plot(x= df$CGPA, y=df$Chance.of.Admit)
abline(lin_model_gre, col="red", lwd=5)
y_predict = predict(lin_model_gre)
fit_coeff = lin_model_gre$coefficients
n = nrow(df)
B = 10000
# Residual plot
plot(x=df$CGPA, y=lin_model_gre$residuals)

# 90% CI of the slope
slope_fit = summary(lin_model_gre)$coeff[2,1]
slope_se = summary(lin_model_gre)$coeff[2,2]
slope_fit-qnorm(0.95)*slope_se
# lower bound
slope_fit+qnorm(0.95)*slope_se
# upper bound

# Empirical Bootstrap
coeff_BT = matrix(NA, nrow=B, ncol=2)
for(i_BT in 1:B){
  w = sample(n,n,replace=T)
  data1_BT = df[w,]
  fit_BT = lm(Chance.of.Admit~CGPA, data=data1_BT)
  coeff_BT[i_BT,] = fit_BT$coefficients
}
colnames(coeff_BT) = c("Intercept","Slope")
# Histogram for intercept
hist(coeff_BT[,'Intercept'], col="tan")
abline(v=fit_coeff[1], lwd=6, col="purple")
# Histogram for slope
hist(coeff_BT[,'Slope'], col="palegreen")
abline(v=fit_coeff[2], lwd=6, col="brown")
# Plot
plot(coeff_BT, cex=0.5)
points(x=fit_coeff[1], y=fit_coeff[2], cex=5, pch="+", col="red")

# Residual Bootstrap
coeff_BT_res = matrix(NA, nrow=B, ncol=2)
for(i_BT in 1:B){
  w = sample(n,n,replace=T)
  y_bt = y_predict+lin_model_gre$residuals[w]
  data1_BT = data.frame(CGPA=df$CGPA,
                        Chance.of.Admit=y_bt)
  fit_BT = lm(Chance.of.Admit~CGPA, data=data1_BT)
  coeff_BT_res[i_BT,] = fit_BT$coefficients
}
colnames(coeff_BT_res) = c("Intercept","Slope")
# Histogram for intercept
hist(coeff_BT_res[,'Intercept'], col="tan")
abline(v=fit_coeff[1], lwd=6, col="purple")
# Histogram for slope
hist(coeff_BT_res[,'Slope'], col="palegreen")
abline(v=fit_coeff[2], lwd=6, col="brown")
# Plot
plot(coeff_BT_res, cex=0.5)
points(x=fit_coeff[1], y=fit_coeff[2], cex=5, pch="+", col="red")

# Wild bootstrap
B = 10000
coeff_BT_wild = matrix(NA, nrow=B, ncol=2)
for(i_BT in 1:B){
  w = sample(n,n,replace=T)
  y_bt = y_predict+rnorm(n, sd=abs(lin_model_gre$residuals))
  data1_BT = data.frame(CGPA=df$CGPA,
                        Chance.of.Admit=y_bt)
  fit_BT = lm(Chance.of.Admit~CGPA, data=data1_BT)
  coeff_BT_wild[i_BT,] = fit_BT$coefficients
}
colnames(coeff_BT_wild) = c("Intercept","Slope")
# Histogram for intercept
hist(coeff_BT_wild[,'Intercept'], col="tan")
abline(v=fit_coeff[1], lwd=6, col="purple")
# Histogram for slope
hist(coeff_BT_wild[,'Slope'], col="palegreen")
abline(v=fit_coeff[2], lwd=6, col="brown")
# Plot
plot(coeff_BT_wild, cex=0.5)
points(x=fit_coeff[1], y=fit_coeff[2], cex=5, pch="+", col="red")

# Result comparisons
# Variances #
# Empirical
var(coeff_BT[,'Intercept'])
var(coeff_BT[,'Slope'])
# Residual
var(coeff_BT_res[,'Intercept'])
var(coeff_BT_res[,'Slope'])
# Wild
var(coeff_BT_wild[,'Intercept'])
var(coeff_BT_wild[,'Slope'])
# MSEs #
# Empirical
mean((coeff_BT[,'Intercept']-fit_coeff[1])^2)
mean((coeff_BT[,'Slope']-fit_coeff[2])^2)
# Residual
mean((coeff_BT_res[,'Intercept']-fit_coeff[1])^2)
mean((coeff_BT_res[,'Slope']-fit_coeff[2])^2)
# Wild
mean((coeff_BT_wild[,'Intercept']-fit_coeff[1])^2)
mean((coeff_BT_wild[,'Slope']-fit_coeff[2])^2)
# Quantile CIs #
# Asymptotic model-based theory
confint(lin_model_gre,level = 0.9)
# Empirical
quantile(coeff_BT[,'Intercept'],c(0.05,0.95))
quantile(coeff_BT[,'Slope'],c(0.05,0.95))
# Residual
quantile(coeff_BT_res[,'Intercept'],c(0.05,0.95))
quantile(coeff_BT_res[,'Slope'],c(0.05,0.95))
# Wild
quantile(coeff_BT_wild[,'Intercept'],c(0.05,0.95))
quantile(coeff_BT_wild[,'Slope'],c(0.05,0.95))

# Boxplots
# Intercept
intercepts <- list(Empirical=coeff_BT[,'Intercept'], Residual=coeff_BT_res[,'Intercept'], Wild=coeff_BT_wild[,'Intercept'])
box_int=boxplot(intercepts,outline=FALSE,boxwex=0.25,ylab="Intercept",col="gray",plot=FALSE)
bxp(box_int,axes=FALSE)
axis(2)
axis(1,tick=FALSE,labels=c("Empirical","Residual", "Wild"),at=1:3)
stripchart(intercepts,vertical=TRUE,pch=16,col="orange",method="jitter",add=TRUE)
# Slope
slopes <- list(Empirical=coeff_BT[,'Slope'], Residual=coeff_BT_res[,'Slope'], Wild=coeff_BT_wild[,'Slope'])
box_slope=boxplot(slopes,outline=FALSE,boxwex=0.25,ylab="Slope",col="gray",plot=FALSE)
bxp(box_slope,axes=FALSE)
axis(2)
axis(1,tick=FALSE,labels=c("Empirical","Residual", "Wild"),at=1:3)
stripchart(slopes,vertical=TRUE,pch=16,col="light blue",method="jitter",add=TRUE)
```

Research
```{r}
set.seed(5312020)
# Linear regression model
lin_model_gre = lm(Chance.of.Admit~Research, data=df)
summary(lin_model_gre)
plot(x= df$Research, y=df$Chance.of.Admit)
abline(lin_model_gre, col="red", lwd=5)
y_predict = predict(lin_model_gre)
fit_coeff = lin_model_gre$coefficients
n = nrow(df)
B = 10000
# Residual plot
plot(x=df$Research, y=lin_model_gre$residuals)

# 90% CI of the slope
slope_fit = summary(lin_model_gre)$coeff[2,1]
slope_se = summary(lin_model_gre)$coeff[2,2]
slope_fit-qnorm(0.95)*slope_se
# lower bound
slope_fit+qnorm(0.95)*slope_se
# upper bound

# Empirical Bootstrap
coeff_BT = matrix(NA, nrow=B, ncol=2)
for(i_BT in 1:B){
  w = sample(n,n,replace=T)
  data1_BT = df[w,]
  fit_BT = lm(Chance.of.Admit~Research, data=data1_BT)
  coeff_BT[i_BT,] = fit_BT$coefficients
}
colnames(coeff_BT) = c("Intercept","Slope")
# Histogram for intercept
hist(coeff_BT[,'Intercept'], col="tan")
abline(v=fit_coeff[1], lwd=6, col="purple")
# Histogram for slope
hist(coeff_BT[,'Slope'], col="palegreen")
abline(v=fit_coeff[2], lwd=6, col="brown")
# Plot
plot(coeff_BT, cex=0.5)
points(x=fit_coeff[1], y=fit_coeff[2], cex=5, pch="+", col="red")

# Residual Bootstrap
coeff_BT_res = matrix(NA, nrow=B, ncol=2)
for(i_BT in 1:B){
  w = sample(n,n,replace=T)
  y_bt = y_predict+lin_model_gre$residuals[w]
  data1_BT = data.frame(Research=df$Research,
                        Chance.of.Admit=y_bt)
  fit_BT = lm(Chance.of.Admit~Research, data=data1_BT)
  coeff_BT_res[i_BT,] = fit_BT$coefficients
}
colnames(coeff_BT_res) = c("Intercept","Slope")
# Histogram for intercept
hist(coeff_BT_res[,'Intercept'], col="tan")
abline(v=fit_coeff[1], lwd=6, col="purple")
# Histogram for slope
hist(coeff_BT_res[,'Slope'], col="palegreen")
abline(v=fit_coeff[2], lwd=6, col="brown")
# Plot
plot(coeff_BT_res, cex=0.5)
points(x=fit_coeff[1], y=fit_coeff[2], cex=5, pch="+", col="red")

# Wild bootstrap
B = 10000
coeff_BT_wild = matrix(NA, nrow=B, ncol=2)
for(i_BT in 1:B){
  w = sample(n,n,replace=T)
  y_bt = y_predict+rnorm(n, sd=abs(lin_model_gre$residuals))
  data1_BT = data.frame(Research=df$Research,
                        Chance.of.Admit=y_bt)
  fit_BT = lm(Chance.of.Admit~Research, data=data1_BT)
  coeff_BT_wild[i_BT,] = fit_BT$coefficients
}
colnames(coeff_BT_wild) = c("Intercept","Slope")
# Histogram for intercept
hist(coeff_BT_wild[,'Intercept'], col="tan")
abline(v=fit_coeff[1], lwd=6, col="purple")
# Histogram for slope
hist(coeff_BT_wild[,'Slope'], col="palegreen")
abline(v=fit_coeff[2], lwd=6, col="brown")
# Plot
plot(coeff_BT_wild, cex=0.5)
points(x=fit_coeff[1], y=fit_coeff[2], cex=5, pch="+", col="red")

# Result comparisons
# Variances #
# Empirical
var(coeff_BT[,'Intercept'])
var(coeff_BT[,'Slope'])
# Residual
var(coeff_BT_res[,'Intercept'])
var(coeff_BT_res[,'Slope'])
# Wild
var(coeff_BT_wild[,'Intercept'])
var(coeff_BT_wild[,'Slope'])
# MSEs #
# Empirical
mean((coeff_BT[,'Intercept']-fit_coeff[1])^2)
mean((coeff_BT[,'Slope']-fit_coeff[2])^2)
# Residual
mean((coeff_BT_res[,'Intercept']-fit_coeff[1])^2)
mean((coeff_BT_res[,'Slope']-fit_coeff[2])^2)
# Wild
mean((coeff_BT_wild[,'Intercept']-fit_coeff[1])^2)
mean((coeff_BT_wild[,'Slope']-fit_coeff[2])^2)
# Quantile CIs #
# Asymptotic model-based theory
confint(lin_model_gre,level = 0.9)
# Empirical
quantile(coeff_BT[,'Intercept'],c(0.05,0.95))
quantile(coeff_BT[,'Slope'],c(0.05,0.95))
# Residual
quantile(coeff_BT_res[,'Intercept'],c(0.05,0.95))
quantile(coeff_BT_res[,'Slope'],c(0.05,0.95))
# Wild
quantile(coeff_BT_wild[,'Intercept'],c(0.05,0.95))
quantile(coeff_BT_wild[,'Slope'],c(0.05,0.95))

# Boxplots
# Intercept
intercepts <- list(Empirical=coeff_BT[,'Intercept'], Residual=coeff_BT_res[,'Intercept'], Wild=coeff_BT_wild[,'Intercept'])
box_int=boxplot(intercepts,outline=FALSE,boxwex=0.25,ylab="Intercept",col="gray",plot=FALSE)
bxp(box_int,axes=FALSE)
axis(2)
axis(1,tick=FALSE,labels=c("Empirical","Residual", "Wild"),at=1:3)
stripchart(intercepts,vertical=TRUE,pch=16,col="orange",method="jitter",add=TRUE)
# Slope
slopes <- list(Empirical=coeff_BT[,'Slope'], Residual=coeff_BT_res[,'Slope'], Wild=coeff_BT_wild[,'Slope'])
box_slope=boxplot(slopes,outline=FALSE,boxwex=0.25,ylab="Slope",col="gray",plot=FALSE)
bxp(box_slope,axes=FALSE)
axis(2)
axis(1,tick=FALSE,labels=c("Empirical","Residual", "Wild"),at=1:3)
stripchart(slopes,vertical=TRUE,pch=16,col="light blue",method="jitter",add=TRUE)
```

